### ISSUE TITLE
Fix intermittent override

### ISSUE THREAD

**Issue by wolfgang42** [wolfgang42/identfavicon-quantum#2]
Sometimes the extension generates a favicon for a site that already has one. I don't know why, but I haven't investigated either.

It might also help to see what the Favioli Chrome extension does to check: https://github.com/ivebencrazy/favioli

**Comment by xuhcc** [comment]
After upgrading to Firefox 63 it started to happen more often. For example, GitHub is affected - sometimes it shows proper octocat icon, but most of the time I see an identicon.

I tried Favioli (Firefox version is available now), it has this problem too, although on fewer websites (not on GitHub).

**Comment by wolfgang42** [comment]
I agree, I've also noticed that it's gotten worse in the last few weeks. It's good to know that Favioli also has the same problem. Firefox bug report here: [Bug 1417721: tabs.Tab.favIconUrl intermittently returns undefined even though favicon is showing in tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1417721). I'll follow up on that bug and see what I can do to get someone to look at it.

**Comment by xuhcc** [comment]
I reported this problem to Favioli project, and they released a fix: https://github.com/ivebencrazy/favioli/pull/46

**Comment by wolfgang42** [comment]
Hmm, interesting. I see that they're working around this by checking for a `<link rel="icon">`, which should be pretty easy to add to my extension. I'll have a go at fixing this tonight.

**Comment by wolfgang42** [comment]
I've just released version 1.1, which has a fix for this bug. Thanks for the help!

**Comment by xuhcc** [comment]
Thank you!

**Comment by wolfgang42** [comment]
This is still happening for certain sites, I've opened #6 to continue tracking this problem.
