### ISSUE TITLE
Not working for all sites

### ISSUE THREAD

**Issue by rayman89** [wolfgang42/identfavicon-quantum#3]
Doesn't work in some sites like https://feheroes.gamepedia.com/Arena_tier_list
https://www.ign.com/wikis/super-smash-bros-switch/World_of_Light_Character_Unlocks_And_Map
https://wednesdaydowntownp.wixsite.com/home

Also It seems like this addon makes webpages load times considerably longer than usual.

**Comment by wolfgang42** [comment]
The sites you linked all have their own favicons, so this extension shouldn't do anything to them. What behaviour are you seeing?

Regarding the longer loading times, I have not seen this behaviour and I'm not sure what would cause it. How much longer does it seem to take, and does this happen on all sites or only certain ones?

**Comment by rayman89** [comment]
I noticed a filterlist on my adblock was messing with the pages and probably your addon and was blocking those favicons I disabled that and it all worked properly. Sorry for the false positive.

**Comment by wolfgang42** [comment]
Glad to hear that you got the problem sorted out.
