### ISSUE TITLE
How to reset Icon?

### ISSUE THREAD

**Issue by musbach** [wolfgang42/identfavicon-quantum#4]
Hi,
Thanks for the great extension. How can I reset the icon. For some reason the google icon wasn't set in Firefox and a new icon was generated. Now I want to have the normal icon back. How can I do it?
Kind regards
Frank

**Comment by wolfgang42** [comment]
I'm not sure what you mean by "reset the icon". Do you mean that the Google icon has been replaced by a generated one?

**Comment by wolfgang42** [comment]
Since I haven't heard back from you, I'm going to close this ticket. Please see #6 for info about sites having their favicon generated when it shouldn't be, or reopen this ticket if you had a different question.
